// 財務計算規則（task 10.1）。逐條對照舊平台：
//   - 稅務預留：gas/Code.gs recalcTaxReserveForShow
//   - 共同基金、各專案損益、成員年度報表：js/analytics.js loadAnalytics / renderShowPnl / renderMemberEarnings
//   - 代墊結清狀態（成員層級 FIFO）：js/transaction.js deriveSettleStatus
// 舊規則怎麼算這裡就怎麼算（包含四捨五入的位置），改這裡前先確認舊平台的行為。

export const MEMBERS = ["傑哥", "柏文", "巧達", "芭樂", "又又", "兔子", "大弋", "竹節蟲"] as const;
export const TAX_RESERVE_RATE = 0.03;
export const TAX_RESERVE_CATEGORY = "稅務預留";
export const TAX_RESERVE_NOTE = "系統自動：營所稅預留 3%";
export const FUND_SHOW_NAME = "共同基金支出";
export const COMMON_FUND_RATE = 0.2;
export const INCOME_CATEGORIES = ["演出票房", "付費會員", "商演合作", "周邊商品", "品牌贊助", "其他收入"] as const;
export const EXPENSE_CATEGORIES = ["場地租借", "工作人員", "設備道具", "剪輯製作", "行政雜支", "平台手續", "稅務預留", "其他支出"] as const;

export type Tx = {
  id: string;
  showName: string;
  category: string;
  notes: string;
  amount: number;
  advancedBy: string | null;
  excludedMembers: string[]; // 空陣列 = 全員共同
  date: string; // YYYY-MM-DD
  recordedBy: string | null;
  paidByFund: boolean;
  autoGenerated: boolean;
  sortOrder: number; // 原 Sheet 列順序
};
export type Ledger = { id: string; member: string; amount: number; date: string; notes: string; sortOrder: number };

const isShared = (t: Pick<Tx, "excludedMembers">) => t.excludedMembers.length === 0;

/** 稅務預留：某專案依「排除成員」分組加總收入，每組一筆 -round(3%)，日期取該組最新收入日。共同基金支出專案不提列。 */
export type ReserveGroup = { excludedMembers: string[]; amount: number; date: string };
export function taxReservesForShow(showName: string, showTxs: Tx[]): ReserveGroup[] {
  if (!showName || showName === FUND_SHOW_NAME) return [];
  const groups = new Map<string, { excluded: string[]; total: number; latest: string }>();
  for (const t of showTxs) {
    if (t.autoGenerated && t.category === TAX_RESERVE_CATEGORY) continue; // 舊邏輯先刪掉舊的自動預留再算
    if (t.amount <= 0) continue;
    const key = t.excludedMembers.join(",");
    const g = groups.get(key) ?? { excluded: t.excludedMembers, total: 0, latest: t.date };
    g.total += t.amount;
    if (t.date > g.latest) g.latest = t.date;
    groups.set(key, g);
  }
  const out: ReserveGroup[] = [];
  for (const g of groups.values()) {
    const reserve = Math.round(g.total * TAX_RESERVE_RATE);
    if (reserve <= 0) continue;
    out.push({ excludedMembers: g.excluded, amount: -reserve, date: g.latest });
  }
  return out;
}

export type Summary = { totalIncome: number; totalExpense: number; netProfit: number };
export function yearSummary(txs: Tx[]): Summary {
  const totalIncome = txs.filter((t) => t.amount > 0).reduce((s, t) => s + t.amount, 0);
  const totalExpense = txs.filter((t) => t.amount < 0).reduce((s, t) => s + t.amount, 0);
  return { totalIncome, totalExpense, netProfit: totalIncome + totalExpense };
}

export type CommonFund = {
  commonIncome: number; commonExpense: number; commonNetProfit: number;
  fundReserved: number; fundUsed: number; fundBalance: number; distributableCommonNet: number;
};
export function commonFund(txs: Tx[]): CommonFund {
  // paidByFund 支出不計入共同支出（避免雙扣），只算進「基金已動用」
  const commonIncome = txs.filter((t) => t.amount > 0 && isShared(t) && !t.paidByFund).reduce((s, t) => s + t.amount, 0);
  const commonExpense = txs.filter((t) => t.amount < 0 && isShared(t) && !t.paidByFund).reduce((s, t) => s + t.amount, 0);
  const commonNetProfit = commonIncome + commonExpense;
  const fundReserved = commonNetProfit * COMMON_FUND_RATE;
  const fundUsed = txs.filter((t) => t.amount < 0 && t.paidByFund).reduce((s, t) => s + Math.abs(t.amount), 0);
  return {
    commonIncome, commonExpense, commonNetProfit, fundReserved, fundUsed,
    fundBalance: fundReserved - fundUsed,
    distributableCommonNet: commonNetProfit * (1 - COMMON_FUND_RATE),
  };
}

export type ShowPnl = { name: string; income: number; expense: number; net: number };
export function showPnl(txs: Tx[]): ShowPnl[] {
  const map = new Map<string, { income: number; expense: number }>();
  for (const t of txs) {
    const s = map.get(t.showName) ?? { income: 0, expense: 0 };
    if (t.amount > 0) s.income += t.amount;
    else s.expense += t.amount;
    map.set(t.showName, s);
  }
  return [...map.entries()].map(([name, d]) => ({ name, income: d.income, expense: d.expense, net: d.income + d.expense }));
}

export type MemberRow = {
  name: string; settled: number; unsettledNet: number; advanceTotal: number;
  advanceCleared: number; advanceUnsettled: number; annualNet: number;
};
export function memberEarnings(txs: Tx[], settlements: Ledger[], reimbursements: Ledger[]): MemberRow[] {
  const { distributableCommonNet } = commonFund(txs);
  const zero = () => Object.fromEntries(MEMBERS.map((m) => [m, 0])) as Record<string, number>;
  const nonSharedIncome = zero();
  const nonSharedExpense = zero();
  for (const t of txs) {
    if (isShared(t) || t.amount === 0) continue;
    const included = MEMBERS.filter((m) => !t.excludedMembers.includes(m));
    const share = included.length > 0 ? t.amount / included.length : 0;
    const bucket = t.amount > 0 ? nonSharedIncome : nonSharedExpense;
    for (const m of included) bucket[m] += share;
  }
  const settled = zero();
  for (const s of settlements) if (s.member in settled) settled[s.member] += s.amount;
  const advanceTotal = zero();
  for (const t of txs) if (t.advancedBy && t.advancedBy in advanceTotal) advanceTotal[t.advancedBy] += Math.abs(t.amount);
  const reimbursed = zero();
  for (const r of reimbursements) if (r.member in reimbursed) reimbursed[r.member] += r.amount;

  return MEMBERS.map((m) => {
    const commonShare = distributableCommonNet / MEMBERS.length;
    const annualNet = Math.round(commonShare + nonSharedIncome[m] + nonSharedExpense[m]);
    const st = Math.round(settled[m]);
    const advT = Math.round(advanceTotal[m]);
    const advC = Math.round(reimbursed[m]);
    return { name: m, settled: st, unsettledNet: annualNet - st, advanceTotal: advT, advanceCleared: advC, advanceUnsettled: advT - advC, annualNet };
  });
}

/** 代墊結清狀態：各成員還款池 = 代墊還款帳本加總；該成員所有代墊交易依日期、同日依列順序，由舊到新沖銷。 */
export type SettleStatus = { status: "settled" | "partial" | "unsettled"; reimbursedAmount: number };
export function deriveSettleStatus(txs: Tx[], reimbursements: Ledger[]): Map<string, SettleStatus> {
  const result = new Map<string, SettleStatus>();
  const pools: Record<string, number> = {};
  for (const r of reimbursements) pools[r.member] = (pools[r.member] ?? 0) + r.amount;
  const byMember = new Map<string, Tx[]>();
  for (const t of txs) {
    if (!t.advancedBy) continue;
    byMember.set(t.advancedBy, [...(byMember.get(t.advancedBy) ?? []), t]);
  }
  for (const [member, advances] of byMember) {
    advances.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : a.sortOrder - b.sortOrder));
    let pool = pools[member] ?? 0;
    for (const t of advances) {
      const amt = Math.abs(t.amount);
      if (pool >= amt) {
        result.set(t.id, { status: "settled", reimbursedAmount: amt });
        pool -= amt;
      } else if (pool > 0) {
        result.set(t.id, { status: "partial", reimbursedAmount: pool });
        pool = 0;
      } else {
        result.set(t.id, { status: "unsettled", reimbursedAmount: 0 });
      }
    }
  }
  return result;
}

/** 收入／支出分類佔比（js/analytics.js renderPieChart）：不在固定分類裡的歸到「其他收入／其他支出」，依佔比由高到低。 */
export type CategoryShare = { name: string; amount: number; pct: number };
export function categoryShares(txs: Tx[], type: "income" | "expense"): CategoryShare[] {
  const fixed: readonly string[] = type === "income" ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;
  const fallback = type === "income" ? "其他收入" : "其他支出";
  const items = txs.filter((t) => (type === "income" ? t.amount > 0 : t.amount < 0));
  const total = Math.abs(items.reduce((s, t) => s + t.amount, 0));
  if (total === 0) return [];
  const groups = new Map<string, number>(fixed.map((c) => [c, 0]));
  for (const t of items) {
    const key = groups.has(t.category) ? t.category : fallback;
    groups.set(key, (groups.get(key) ?? 0) + Math.abs(t.amount));
  }
  return fixed
    .map((name) => ({ name, amount: groups.get(name) ?? 0, pct: ((groups.get(name) ?? 0) / total) * 100 }))
    .filter((c) => c.amount > 0)
    .sort((a, b) => b.pct - a.pct);
}
