import { test } from "node:test";
import assert from "node:assert/strict";
import { commonFund, deriveSettleStatus, memberEarnings, taxReservesForShow, type Ledger, type Tx } from "./calc.ts";

let seq = 0;
const tx = (o: Partial<Tx>): Tx => ({
  id: `t${++seq}`, showName: "10 月號", category: "演出票房", notes: "", amount: 0, advancedBy: null, excludedMembers: [],
  date: "2026-10-01", recordedBy: null, paidByFund: false, autoGenerated: false, sortOrder: seq, ...o,
});
const led = (member: string, amount: number): Ledger => ({ id: `l${++seq}`, member, amount, date: "2026-10-05", notes: "", sortOrder: seq });

test("代墊 FIFO：同一天依列順序沖銷，還款不夠時第一筆部分結清", () => {
  const a = tx({ amount: -300, advancedBy: "柏文", date: "2026-10-01", sortOrder: 10 });
  const b = tx({ amount: -500, advancedBy: "柏文", date: "2026-10-01", sortOrder: 11 });
  const c = tx({ amount: -200, advancedBy: "柏文", date: "2026-09-30", sortOrder: 99 });
  const st = deriveSettleStatus([b, a, c], [led("柏文", 400)]);
  assert.deepEqual(st.get(c.id), { status: "settled", reimbursedAmount: 200 }); // 日期最早先沖
  assert.deepEqual(st.get(a.id), { status: "partial", reimbursedAmount: 200 }); // 同日列順序較前
  assert.deepEqual(st.get(b.id), { status: "unsettled", reimbursedAmount: 0 });
});

test("稅務預留：依排除成員分組、取最新日期、四捨五入、忽略舊的自動預留與共同基金專案", () => {
  const rows = [
    tx({ amount: 10000, date: "2026-10-01" }),
    tx({ amount: 5050, date: "2026-10-03" }),
    tx({ amount: 2000, excludedMembers: ["傑哥", "柏文"], date: "2026-10-02" }),
    tx({ amount: -300, category: "稅務預留", autoGenerated: true }),
    tx({ amount: -800 }),
  ];
  assert.deepEqual(taxReservesForShow("10 月號", rows), [
    { excludedMembers: [], amount: -452, date: "2026-10-03" }, // round(15050 × 3%) = 451.5 → 452
    { excludedMembers: ["傑哥", "柏文"], amount: -60, date: "2026-10-02" },
  ]);
  assert.deepEqual(taxReservesForShow("共同基金支出", rows), []);
});

test("共同基金：共同基金支付的支出不算共同支出，只算已動用", () => {
  const f = commonFund([tx({ amount: 10000 }), tx({ amount: -2000 }), tx({ amount: -1000, paidByFund: true })]);
  assert.equal(f.commonNetProfit, 8000);
  assert.equal(f.fundReserved, 1600);
  assert.equal(f.fundUsed, 1000);
  assert.equal(f.fundBalance, 600);
  assert.equal(f.distributableCommonNet, 6400);
});

test("成員分配：非共同收入只分給沒被排除的成員；結算與代墊分開計", () => {
  const rows = [tx({ amount: 8000 }), tx({ amount: 600, excludedMembers: ["巧達", "芭樂", "又又", "兔子", "大弋", "竹節蟲"] }), tx({ amount: -100, advancedBy: "柏文" })];
  const m = Object.fromEntries(memberEarnings(rows, [led("柏文", 500)], [led("柏文", 100)]).map((r) => [r.name, r]));
  // 共同淨利 (8000-100)=7900 × 80% / 8 = 790；柏文另得 600/2 = 300
  assert.equal(m["柏文"].annualNet, 1090);
  assert.equal(m["柏文"].settled, 500);
  assert.equal(m["柏文"].unsettledNet, 590);
  assert.equal(m["柏文"].advanceUnsettled, 0);
  assert.equal(m["巧達"].annualNet, 790);
});

import { categoryShares } from "./calc.ts";
test("分類佔比：未知分類歸到其他、依佔比排序", () => {
  const r = categoryShares([tx({ amount: 300, category: "演出票房" }), tx({ amount: 100, category: "神秘收入" }), tx({ amount: -50 })], "income");
  assert.deepEqual(r.map((c) => [c.name, c.amount, Math.round(c.pct)]), [["演出票房", 300, 75], ["其他收入", 100, 25]]);
});
