// 財務資料的讀取與寫入（伺服器端）。所有寫入以本人為 actor；稅務預留由 syncTaxReserve 以 system 名義同步。
import { db, type Actor } from "../supabase.ts";
import { TAX_RESERVE_CATEGORY, TAX_RESERVE_NOTE, taxReservesForShow, type Ledger, type Tx } from "./calc.ts";
import { planReserveSync } from "./reserve.ts";

export type TxRow = Tx & { showId: string };

type DbTx = {
  id: string; show_id: string; category: string; notes: string; amount: string | number; advanced_by: string | null;
  excluded_members: string[]; date: string; recorded_by: string | null; paid_by_fund: boolean; auto_generated: boolean;
  sort_order: number; shows: { name: string } | null;
};
const TX_SELECT = "id, show_id, category, notes, amount, advanced_by, excluded_members, date, recorded_by, paid_by_fund, auto_generated, sort_order, shows(name)";

function toTx(r: DbTx): TxRow {
  return {
    id: r.id, showId: r.show_id, showName: r.shows?.name ?? "", category: r.category, notes: r.notes, amount: Number(r.amount),
    advancedBy: r.advanced_by, excludedMembers: r.excluded_members ?? [], date: r.date, recordedBy: r.recorded_by,
    paidByFund: r.paid_by_fund, autoGenerated: r.auto_generated, sortOrder: Number(r.sort_order),
  };
}

export async function listTransactions(actor: Actor, showId?: string): Promise<TxRow[]> {
  let q = db(actor).from("transactions").select(TX_SELECT).is("deleted_at", null).order("sort_order");
  if (showId) q = q.eq("show_id", showId);
  const { data, error } = await q.returns<DbTx[]>();
  if (error) throw new Error(`list transactions: ${error.message}`);
  return (data ?? []).map(toTx);
}

export async function listLedger(actor: Actor, table: "settlements" | "advance_repayments"): Promise<Ledger[]> {
  const { data, error } = await db(actor).from(table).select("id, member, amount, date, notes, sort_order").is("deleted_at", null).order("sort_order");
  if (error) throw new Error(`list ${table}: ${error.message}`);
  return (data ?? []).map((r: { id: string; member: string; amount: string | number; date: string; notes: string; sort_order: number }) => ({
    id: r.id, member: r.member, amount: Number(r.amount), date: r.date, notes: r.notes, sortOrder: Number(r.sort_order),
  }));
}

/** 重算某專案的稅務預留（舊 GAS recalcTaxReserveForShow 的等價版本）。 */
export async function syncTaxReserve(actor: Actor, showId: string): Promise<void> {
  const client = db(actor);
  const { data: show, error: e0 } = await client.from("shows").select("name").eq("id", showId).single();
  if (e0 || !show) throw new Error(`read show: ${e0?.message}`);
  const txs = await listTransactions(actor, showId);
  const desired = taxReservesForShow(show.name, txs);
  const existing = txs
    .filter((t) => t.autoGenerated && t.category === TAX_RESERVE_CATEGORY)
    .map((t) => ({ id: t.id, excludedMembers: t.excludedMembers, amount: t.amount, date: t.date }));
  const plan = planReserveSync(existing, desired);
  for (const u of plan.updates) {
    const { error } = await client.from("transactions").update({ amount: u.amount, date: u.date }).eq("id", u.id);
    if (error) throw new Error(`update reserve: ${error.message}`);
  }
  if (plan.inserts.length) {
    const { error } = await client.from("transactions").insert(
      plan.inserts.map((g) => ({
        show_id: showId, category: TAX_RESERVE_CATEGORY, notes: TAX_RESERVE_NOTE, amount: g.amount, advanced_by: null,
        excluded_members: g.excludedMembers, date: g.date, recorded_by: "系統", paid_by_fund: false, auto_generated: true,
      })),
    );
    if (error) throw new Error(`insert reserve: ${error.message}`);
  }
  if (plan.removes.length) {
    const { error } = await client.from("transactions").update({ deleted_at: new Date().toISOString(), deleted_by: "系統" }).in("id", plan.removes);
    if (error) throw new Error(`remove reserve: ${error.message}`);
  }
}
