// 讀舊 Google Sheet 匯出的 xlsx（搬家與對帳共用）。保留每張表的列順序。
import * as XLSX from "xlsx";

export type SheetTx = {
  row: number; // 原 Sheet 列號（2 起）
  id: string; showName: string; category: string; notes: string; amount: number;
  advancedBy: string; excludedMembers: string; settledText: string; date: string;
  recordedBy: string; paidByFund: boolean; autoGenerated: boolean;
};
export type SheetLedger = { row: number; member: string; amount: number; date: string; notes: string };
export type SheetShow = { row: number; name: string; createdDate: string; status: string };
export type SheetData = { shows: SheetShow[]; transactions: SheetTx[]; settlements: SheetLedger[]; repayments: SheetLedger[] };

const bool = (v: unknown) => v === true || String(v).toUpperCase() === "TRUE";
const str = (v: unknown) => (v === undefined || v === null ? "" : String(v).trim());
function num(v: unknown, where: string): number {
  const n = Number(String(v).replace(/,/g, ""));
  if (!Number.isFinite(n)) throw new Error(`金額不是數字：${where} = ${String(v)}`);
  return n;
}
function date(v: unknown, where: string): string {
  // 讀格子的原始值：Excel 日期序號（不同分頁顯示格式不同，例如 yyyy-mm-dd 與 mm-dd-yy，所以不能讀顯示文字）
  if (typeof v === "number") {
    const p = XLSX.SSF.parse_date_code(v);
    if (!p) throw new Error(`日期格式不對：${where} = ${v}`);
    return `${p.y}-${String(p.m).padStart(2, "0")}-${String(p.d).padStart(2, "0")}`;
  }
  const s = str(v);
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(s);
  if (!m) throw new Error(`日期格式不對：${where} = ${s}`);
  return `${m[1]}-${m[2]}-${m[3]}`;
}

function rows(wb: XLSX.WorkBook, name: string): unknown[][] {
  const ws = wb.Sheets[name];
  if (!ws) throw new Error(`找不到工作表「${name}」`);
  return XLSX.utils.sheet_to_json<unknown[]>(ws, { header: 1, raw: true, blankrows: true });
}

export function readLegacyWorkbook(buffer: Uint8Array | ArrayBuffer): SheetData {
  const wb = XLSX.read(buffer, { type: "array", cellDates: false });
  const out: SheetData = { shows: [], transactions: [], settlements: [], repayments: [] };

  rows(wb, "專案清單").forEach((r, i) => {
    if (i === 0 || !str(r[0])) return;
    out.shows.push({ row: i + 1, name: str(r[0]), createdDate: str(r[1]) ? date(r[1], `專案清單 第${i + 1}列`) : "", status: str(r[2]) });
  });
  rows(wb, "收支紀錄").forEach((r, i) => {
    if (i === 0 || r.every((v) => str(v) === "")) return;
    const where = `收支紀錄 第${i + 1}列`;
    out.transactions.push({
      row: i + 1, id: str(r[11]), showName: str(r[0]), category: str(r[1]), notes: str(r[2]),
      amount: num(r[3], where), advancedBy: str(r[4]), excludedMembers: str(r[5]), settledText: str(r[6]),
      date: date(r[7], where), recordedBy: str(r[8]), paidByFund: bool(r[9]), autoGenerated: bool(r[10]),
    });
  });
  for (const [sheet, key] of [["成員結算", "settlements"], ["代墊還款", "repayments"]] as const) {
    rows(wb, sheet).forEach((r, i) => {
      if (i === 0 || r.every((v) => str(v) === "")) return;
      const where = `${sheet} 第${i + 1}列`;
      out[key].push({ row: i + 1, member: str(r[0]), amount: num(r[1], where), date: date(r[2], where), notes: str(r[3]) });
    });
  }
  return out;
}
