"use client";
// 收支紀錄的互動層：點一筆打開編輯面板、右下角新增；刪除先在畫面上消失（樂觀更新）。
import { useOptimistic, useState, useTransition } from "react";
import { deleteTransaction, saveTransaction, type ActionResult } from "@/app/(app)/finance/actions";
import { formatMonthDay } from "@/lib/dates";

export type BoardTx = {
  id: string; category: string; notes: string; amount: number; advancedBy: string | null; excludedMembers: string[];
  date: string; recordedBy: string | null; paidByFund: boolean; autoGenerated: boolean;
  settle: { status: "settled" | "partial" | "unsettled"; reimbursedAmount: number } | null;
};

const SETTLE_LABEL = { settled: "已結清", partial: "部分結清", unsettled: "未結清" } as const;
const money = (n: number) => `${n > 0 ? "+" : n < 0 ? "-" : ""}$${Math.abs(n).toLocaleString()}`;

function allocationText(t: BoardTx, members: readonly string[]): string | null {
  if (t.paidByFund) return "共同基金支付";
  if (!t.excludedMembers.length) return null;
  const included = members.filter((m) => !t.excludedMembers.includes(m));
  return `只分給 ${included.join("、")}`;
}

export default function TxBoard(props: {
  showId: string; showName: string; txs: BoardTx[]; members: readonly string[];
  incomeCategories: readonly string[]; expenseCategories: readonly string[]; me: string; today: string;
}) {
  const [txs, removeOptimistic] = useOptimistic(props.txs, (list: BoardTx[], id: string) => list.filter((t) => t.id !== id));
  const [, startTransition] = useTransition();
  const [editing, setEditing] = useState<BoardTx | "new" | null>(null);
  const [error, setError] = useState<string | null>(null);

  const run = (action: () => Promise<ActionResult>, optimistic?: () => void) => {
    setError(null);
    startTransition(async () => {
      optimistic?.();
      try {
        const r = await action();
        if (!r.ok) setError(r.error);
      } catch {
        setError("剛剛的操作沒有存成功，請再試一次");
      }
    });
  };

  return (
    <>
      {error ? <div className="notice" role="alert">{error}</div> : null}
      {txs.length === 0 ? <p className="empty">這個專案還沒有收支</p> : null}
      {txs.map((t) => {
        const alloc = allocationText(t, props.members);
        return (
          <button
            key={t.id}
            type="button"
            className="card row"
            onClick={() => (t.autoGenerated ? setError("系統自動產生的稅務預留會隨收入自動調整，不能手動修改") : setEditing(t))}
            style={{ width: "100%", border: 0, textAlign: "left", cursor: "pointer", font: "inherit", color: "inherit" }}
          >
            <span className="row-main">
              <span className="title" style={{ display: "block" }}>{t.notes || t.category}</span>
              <span className="meta">
                <span className="tag">{t.category}</span>
                <span>{formatMonthDay(t.date)}</span>
                {t.advancedBy ? <span>{t.advancedBy} 墊</span> : null}
                {t.settle ? <span className={`badge ${t.settle.status}`}>{SETTLE_LABEL[t.settle.status]}</span> : null}
                {alloc ? <span>{alloc}</span> : null}
                {t.autoGenerated ? <span>系統自動</span> : null}
              </span>
            </span>
            <span className={`amount ${t.amount >= 0 ? "pos" : "neg"}`}>{money(t.amount)}</span>
          </button>
        );
      })}

      <button className="fab" type="button" aria-label="新增收支" onClick={() => setEditing("new")} style={{ border: 0, cursor: "pointer" }}>+</button>

      {editing ? (
        <TxSheet
          key={editing === "new" ? "new" : editing.id}
          tx={editing === "new" ? undefined : editing}
          {...props}
          onClose={() => setEditing(null)}
          onSave={(fd) => {
            setEditing(null);
            run(() => saveTransaction(fd));
          }}
          onDelete={(id) => {
            setEditing(null);
            const fd = new FormData();
            fd.set("id", id);
            run(() => deleteTransaction(fd), () => removeOptimistic(id));
          }}
        />
      ) : null}
    </>
  );
}

function TxSheet(props: {
  tx?: BoardTx; showId: string; showName: string; members: readonly string[]; incomeCategories: readonly string[];
  expenseCategories: readonly string[]; me: string; today: string;
  onClose: () => void; onSave: (fd: FormData) => void; onDelete: (id: string) => void;
}) {
  const t = props.tx;
  const [kind, setKind] = useState<"income" | "expense">(t && t.amount > 0 ? "income" : "expense");
  const [fund, setFund] = useState(!!t?.paidByFund);
  const [advanced, setAdvanced] = useState(t?.advancedBy && !props.members.includes(t.advancedBy) ? "__other" : (t?.advancedBy ?? ""));
  const categories = kind === "income" ? props.incomeCategories : props.expenseCategories.filter((c) => c !== "稅務預留");
  const showFund = kind === "expense";
  const allocate = !(showFund && fund);

  return (
    <div className="sheet-backdrop" onClick={props.onClose}>
      <div className="sheet" role="dialog" aria-modal="true" aria-labelledby="tx-title" onClick={(e) => e.stopPropagation()}>
        <h2 id="tx-title">{t ? "編輯收支" : `新增收支・${props.showName}`}</h2>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            props.onSave(new FormData(e.currentTarget));
          }}
        >
          {t ? <input type="hidden" name="id" value={t.id} /> : <input type="hidden" name="show_id" value={props.showId} />}
          <div className="seg" role="radiogroup" aria-label="收入或支出">
            <label><input type="radio" name="kind" value="expense" checked={kind === "expense"} onChange={() => setKind("expense")} /><span>支出</span></label>
            <label><input type="radio" name="kind" value="income" checked={kind === "income"} onChange={() => setKind("income")} /><span>收入</span></label>
          </div>
          <label className="field">
            <span>分類</span>
            <select className="select" name="category" defaultValue={t && categories.includes(t.category) ? t.category : categories[0]} key={kind}>
              {categories.map((c) => <option key={c} value={c}>{c}</option>)}
            </select>
          </label>
          <label className="field">
            <span>金額（不用加正負號）</span>
            <input className="input" name="amount" type="number" inputMode="decimal" min="1" step="any" required defaultValue={t ? Math.abs(t.amount) : ""} />
          </label>
          <label className="field">
            <span>備註</span>
            <input className="input" name="notes" defaultValue={t?.notes ?? ""} maxLength={200} />
          </label>
          <label className="field">
            <span>日期</span>
            <input className="input" name="date" type="date" required defaultValue={t?.date ?? props.today} />
          </label>
          {showFund ? (
            <label className="check-line">
              <input type="checkbox" name="paid_by_fund" value="1" checked={fund} onChange={(e) => setFund(e.target.checked)} />
              由共同基金支付
            </label>
          ) : null}
          {allocate ? (
            <>
              <label className="field">
                <span>墊款人（沒有人墊就留空）</span>
                <select className="select" name="advanced_by" value={advanced} onChange={(e) => setAdvanced(e.target.value)}>
                  <option value="">沒有人墊款</option>
                  {props.members.map((m) => <option key={m} value={m}>{m}</option>)}
                  <option value="__other">其他人</option>
                </select>
              </label>
              {advanced === "__other" ? (
                <label className="field">
                  <span>墊款人姓名</span>
                  <input className="input" name="advanced_by_other" required defaultValue={t?.advancedBy && !props.members.includes(t.advancedBy) ? t.advancedBy : ""} />
                </label>
              ) : null}
              <fieldset className="field" style={{ border: 0, padding: 0, margin: "0 0 14px" }}>
                <span>分配給（取消勾選 = 這筆不算他的）</span>
                <div className="picks">
                  {props.members.map((m) => (
                    <label key={m} className="pick">
                      <input type="checkbox" name="included" value={m} defaultChecked={!t?.excludedMembers.includes(m)} />
                      <span>{m}</span>
                    </label>
                  ))}
                </div>
              </fieldset>
            </>
          ) : null}
          <label className="field">
            <span>登記人</span>
            <input className="input" name="recorded_by" defaultValue={t?.recordedBy ?? props.me} maxLength={30} />
          </label>
          <div className="actions">
            <button className="btn btn-primary" type="submit">{t ? "儲存" : "新增"}</button>
            <button className="btn btn-ghost" type="button" onClick={props.onClose}>取消</button>
          </div>
        </form>
        {t ? (
          <div className="actions" style={{ marginTop: 16 }}>
            <button className="btn btn-danger" type="button" onClick={() => props.onDelete(t.id)}>刪除這筆</button>
          </div>
        ) : null}
      </div>
    </div>
  );
}
