// 匯出收支 CSV（spec: Login and export events：匯出財務資料要留操作紀錄）。
import { requireAction } from "@/lib/auth/current";
import { listTransactions } from "@/lib/finance/data";
import { logEvent } from "@/lib/audit";

const cell = (v: unknown) => {
  const s = v === null || v === undefined ? "" : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

export async function GET(): Promise<Response> {
  let me;
  try {
    me = await requireAction("finance");
  } catch {
    return new Response("forbidden", { status: 403 });
  }
  const txs = await listTransactions(`user:${me.id}`);
  const header = ["專案名稱", "分類", "備註", "金額", "墊款人", "排除成員", "日期", "登記人", "由共同基金支付", "系統自動", "ID"];
  const lines = txs.map((t) => [t.showName, t.category, t.notes, t.amount, t.advancedBy ?? "", t.excludedMembers.join(","), t.date, t.recordedBy ?? "", t.paidByFund, t.autoGenerated, t.id].map(cell).join(","));
  await logEvent(`user:${me.id}`, "finance.export", { what: "transactions.csv", rows: txs.length });
  return new Response("﻿" + [header.join(","), ...lines].join("\n"), {
    headers: { "Content-Type": "text/csv; charset=utf-8", "Content-Disposition": `attachment; filename="jokesonme-transactions.csv"` },
  });
}
