import { requirePage } from "@/lib/auth/current";
import { listShows } from "@/lib/shows";
import { listLedger, listTransactions } from "@/lib/finance/data";
import { deriveSettleStatus, EXPENSE_CATEGORIES, INCOME_CATEGORIES, MEMBERS } from "@/lib/finance/calc";
import { todayInTaipei } from "@/lib/dates";
import { displayName } from "@/lib/auth/users";
import FinanceHead from "@/components/finance-head";
import TxBoard from "@/components/tx-board";
import ShowPicker from "@/components/show-picker";

const money = (n: number) => `${n > 0 ? "+" : n < 0 ? "-" : ""}$${Math.abs(n).toLocaleString()}`;

export default async function TransactionsPage({ searchParams }: PageProps<"/finance/transactions">) {
  const sp = await searchParams;
  const me = await requirePage("finance", "/finance/transactions");
  const actor = `user:${me.id}` as const;
  const [shows, allTx, repayments] = await Promise.all([listShows(actor), listTransactions(actor), listLedger(actor, "advance_repayments")]);

  // 預設選「最近一筆收支」所在的專案
  const latestShow = [...allTx].sort((a, b) => (b.date + String(b.sortOrder).padStart(12, "0")).localeCompare(a.date + String(a.sortOrder).padStart(12, "0")))[0]?.showId;
  const showId = typeof sp.show === "string" && shows.some((s) => s.id === sp.show) ? sp.show : (latestShow ?? shows[0]?.id ?? "");
  const show = shows.find((s) => s.id === showId);
  const settle = deriveSettleStatus(allTx, repayments); // FIFO 要看該成員所有專案的代墊
  const txs = allTx
    .filter((t) => t.showId === showId)
    .sort((a, b) => (a.date !== b.date ? (a.date < b.date ? 1 : -1) : b.sortOrder - a.sortOrder));
  const income = txs.filter((t) => t.amount > 0).reduce((s, t) => s + t.amount, 0);
  const expense = txs.filter((t) => t.amount < 0).reduce((s, t) => s + t.amount, 0);

  return (
    <main className="page">
      <FinanceHead me={me} active="transactions" title="收支紀錄" />
      <div className="content">
        <div className="toolbar">
          <ShowPicker shows={shows.map((s) => ({ id: s.id, name: s.name }))} value={showId} />
        </div>
        {show ? (
          <>
            <div className="grid-stats" style={{ marginBottom: 12 }}>
              <div className="card"><small>收入</small><span className="amount pos">{money(income)}</span></div>
              <div className="card"><small>支出</small><span className="amount neg">{money(expense)}</span></div>
              <div className="card"><small>淨利</small><span className={`amount ${income + expense >= 0 ? "pos" : "neg"}`}>{money(income + expense)}</span></div>
            </div>
            <TxBoard
              key={showId}
              showId={showId}
              showName={show.name}
              txs={txs.map((t) => ({
                id: t.id, category: t.category, notes: t.notes, amount: t.amount, advancedBy: t.advancedBy, excludedMembers: t.excludedMembers,
                date: t.date, recordedBy: t.recordedBy, paidByFund: t.paidByFund, autoGenerated: t.autoGenerated, settle: settle.get(t.id) ?? null,
              }))}
              members={MEMBERS}
              incomeCategories={INCOME_CATEGORIES}
              expenseCategories={EXPENSE_CATEGORIES}
              me={displayName(me)}
              today={todayInTaipei()}
            />
          </>
        ) : (
          <p className="empty">還沒有專案。到「企劃」新增一個。</p>
        )}
        <a className="toggle-done" href="/api/finance/export">下載全部收支（CSV）</a>
      </div>
    </main>
  );
}
