-- 0006 財務資料表（task 10.2；spec: supabase-data-store、audit-log「Financial soft delete」）
-- 欄位一比一對應舊 Google Sheet。成員一律存名字（傑哥、柏文…），跟舊資料與舊計算邏輯相同。
-- sort_order 保留原 Sheet 列順序：代墊 FIFO 沖銷在同一天時依列順序決定，順序變了結果就會變。
-- 刪除一律是軟刪除（deleted_at），所有加總與列表都要排除已刪除的列。

-- 舊專案清單的列號：搬家時記下，對帳時用來核對專案筆數；平台上新建的專案為 null
alter table shows add column legacy_row int;

create table transactions (
  id               uuid primary key default gen_random_uuid(),   -- 舊資料沿用 Sheet 的 UUID
  show_id          uuid not null references shows(id),
  category         text not null,
  notes            text not null default '',
  amount           numeric(14, 2) not null,                     -- 正數收入、負數支出
  advanced_by      text,                                        -- 墊款人（成員名或其他人名）；共同基金支付時為 null
  excluded_members text[] not null default '{}',                -- 不分配這筆的成員；空陣列 = 全員共同
  date             date not null,
  recorded_by      text,
  paid_by_fund     boolean not null default false,
  auto_generated   boolean not null default false,              -- 系統自動產生的稅務預留
  sort_order       bigint generated by default as identity,
  created_at       timestamptz not null default now(),
  deleted_at       timestamptz,
  deleted_by       text,
  check (not (paid_by_fund and amount > 0)),                    -- 收入不能由共同基金支付
  check (not paid_by_fund or (advanced_by is null and excluded_members = '{}'))
);
create index transactions_show_idx on transactions (show_id) where deleted_at is null;

create table settlements (                                      -- 成員結算（利潤分配，已收款）
  id         uuid primary key default gen_random_uuid(),
  member     text not null,
  amount     numeric(14, 2) not null,                           -- 舊資料有負數校正列，故不限正數
  date       date not null,
  notes      text not null default '',
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by text
);

create table advance_repayments (                               -- 代墊還款帳本
  id         uuid primary key default gen_random_uuid(),
  member     text not null,
  amount     numeric(14, 2) not null check (amount > 0),
  date       date not null,
  notes      text not null default '',
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by text
);

do $$
declare t text;
begin
  foreach t in array array['transactions', 'settlements', 'advance_repayments'] loop
    execute format('alter table %I enable row level security', t);
    execute format('revoke all on %I from public, anon, authenticated', t);
    -- 財務資料不給 delete 權限：只能軟刪除（update deleted_at）
    execute format('grant select, insert, update on %I to service_role', t);
    perform attach_audit(t::regclass);
  end loop;
end $$;

insert into _migrations (name) values ('0006_finance') on conflict do nothing;
