// 檢查每個專案現有的自動稅務預留，是否就是新規則算出來的結果（不需任何調整）。用法：DATABASE_URL=... node scripts/check-tax-reserves.mts
import pg from "pg";
import { taxReservesForShow, TAX_RESERVE_CATEGORY, type Tx } from "../lib/finance/calc.ts";
import { planReserveSync } from "../lib/finance/reserve.ts";
const c = new pg.Client({ connectionString: process.env.DATABASE_URL }); await c.connect();
const { rows } = await c.query(`select t.*, t.amount::float8 as amt, to_char(t.date,'YYYY-MM-DD') as d, s.name as show_name from transactions t join shows s on s.id=t.show_id`);
const byShow = new Map<string, Tx[]>();
for (const r of rows) byShow.set(r.show_name, [...(byShow.get(r.show_name) ?? []), { id: r.id, showName: r.show_name, category: r.category, notes: r.notes, amount: r.amt, advancedBy: r.advanced_by, excludedMembers: r.excluded_members, date: r.d, recordedBy: r.recorded_by, paidByFund: r.paid_by_fund, autoGenerated: r.auto_generated, sortOrder: Number(r.sort_order) }]);
let bad = 0;
for (const [name, txs] of byShow) {
  const existing = txs.filter((t) => t.autoGenerated && t.category === TAX_RESERVE_CATEGORY).map((t) => ({ id: t.id, excludedMembers: t.excludedMembers, amount: t.amount, date: t.date }));
  const plan = planReserveSync(existing, taxReservesForShow(name, txs));
  if (plan.inserts.length || plan.updates.length || plan.removes.length) { bad++; console.log("需要調整：", name, JSON.stringify(plan)); }
}
console.log(`檢查 ${byShow.size} 個專案，${bad} 個與舊系統的稅務預留不同`);
await c.end(); process.exit(bad ? 1 : 0);
