// 對帳的「標準答案」：在隔離環境直接執行舊平台的 js/shared.js 與 js/analytics.js、js/transaction.js 的 deriveSettleStatus，
// 餵入舊 Sheet 匯出的資料（形狀跟舊 GAS getTransactions 回傳的一樣），讀出舊程式畫出來的數字。
// 用法：node scripts/legacy-oracle.mts "../RAW DATA/看我笑話工作室 後勤平台.xlsx" > oracle.json
import { readFileSync } from "node:fs";
import vm from "node:vm";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { readLegacyWorkbook } from "../lib/finance/sheet.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const file = process.argv[2];
if (!file) throw new Error("請給 xlsx 路徑");
const data = readLegacyWorkbook(readFileSync(file));

// 舊 GAS 回傳的形狀（日期在 JSON 裡是 ISO 字串；台北午夜 = 前一天 16:00Z）
const iso = (d: string) => new Date(`${d}T00:00:00+08:00`).toISOString();
const gasTx = data.transactions.map((t) => ({
  id: t.id, showName: t.showName, category: t.category, notes: t.notes, amount: t.amount,
  advancedBy: t.advancedBy, excludedMembers: t.excludedMembers, settled: t.settledText === "已結清",
  date: iso(t.date), recordedBy: t.recordedBy, paidByFund: t.paidByFund, autoGenerated: t.autoGenerated,
}));
const gasLedger = (rows: typeof data.settlements) => rows.map((r) => ({ id: r.row, member: r.member, amount: r.amount, date: iso(r.date), notes: r.notes }));

const elements: Record<string, { innerHTML: string; querySelectorAll: () => never[] }> = {};
const el = (id: string) => (elements[id] ??= { innerHTML: "", querySelectorAll: () => [] });
const ctx = vm.createContext({
  console, Promise, Date, Math, Number, String, Object, Array, Map, Set, JSON, isNaN, setTimeout,
  sessionStorage: { getItem: () => "token" }, localStorage: { getItem: () => null, setItem() {} },
  window: { location: {} }, location: {},
  document: {
    getElementById: el, querySelector: () => null, querySelectorAll: () => [],
    createElement: () => ({ style: {}, classList: { add() {}, remove() {} }, appendChild() {} }),
    body: { appendChild() {} }, addEventListener() {},
  },
  API: {
    getTransactions: async () => ({ success: true, data: gasTx }),
    getSettlements: async () => ({ success: true, data: gasLedger(data.settlements) }),
    getAdvanceReimbursements: async () => ({ success: true, data: gasLedger(data.repayments) }),
  },
});
for (const f of ["js/shared.js"]) vm.runInContext(readFileSync(resolve(ROOT, f), "utf8"), ctx, { filename: f });
// 舊頁面的 IIFE 會呼叫 renderNav 等畫面函式，換成空函式；計算函式維持原樣
vm.runInContext("checkAuth = () => {}; renderNav = () => {}; escapeHtml = (s) => String(s ?? '');", ctx);
vm.runInContext(readFileSync(resolve(ROOT, "js/analytics.js"), "utf8"), ctx, { filename: "js/analytics.js" });
const txSrc = readFileSync(resolve(ROOT, "js/transaction.js"), "utf8");
const fn = txSrc.slice(txSrc.indexOf("function deriveSettleStatus"), txSrc.indexOf("function startEdit"));
vm.runInContext(fn, ctx, { filename: "js/transaction.js#deriveSettleStatus" });

// 圓餅圖要瀏覽器畫布，不影響數字，換成空函式
vm.runInContext("drawPie = () => {};", ctx);
await vm.runInContext("loadAnalytics()", ctx);

const money = (s: string) => Number(s.replace(/[$,+\s]/g, "").replace(/^-/, "-"));
const cells = (html: string) => [...html.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g)].map((m) => m[1].replace(/<[^>]+>/g, "").trim());
const statValues = (html: string) =>
  Object.fromEntries([...html.matchAll(/stat-label">([^<]+)<\/div>\s*<div class="stat-value[^"]*">([^<]+)</g)].map((m) => [m[1].trim(), money(m[2])]));

const memberCells = cells(elements["member-earnings"].innerHTML);
const members = [];
for (let i = 0; i + 5 < memberCells.length; i += 6) {
  members.push({
    name: memberCells[i], settled: money(memberCells[i + 1]), unsettledNet: money(memberCells[i + 2]),
    advanceUnsettled: money(memberCells[i + 3]), advanceCleared: money(memberCells[i + 4]), annualNet: money(memberCells[i + 5]),
  });
}
const pnlCells = cells(elements["show-pnl"].innerHTML);
const shows = [];
for (let i = 0; i + 3 < pnlCells.length; i += 4) {
  if (pnlCells[i] === "合計") continue; // 表格最後一列是合計，不是專案
  shows.push({ name: pnlCells[i], income: money(pnlCells[i + 1]), expense: money(pnlCells[i + 2]), net: money(pnlCells[i + 3]) });
}
const settle = vm.runInContext("deriveSettleStatus", ctx)(gasTx, gasLedger(data.repayments)) as Map<string, unknown>;

console.log(JSON.stringify({
  source: "legacy js/analytics.js + js/transaction.js",
  counts: { shows: data.shows.length, transactions: data.transactions.length, settlements: data.settlements.length, repayments: data.repayments.length },
  summary: statValues(elements["summary-stats"].innerHTML),
  commonFund: statValues(elements["common-fund"].innerHTML),
  members,
  shows,
  settleStatus: Object.fromEntries(settle),
}, null, 2));
