// 一次性搬家（task 10.5；spec: One-time finance migration）：舊 Google Sheet 匯出的 xlsx → Supabase。
//   - 搬：專案清單、收支紀錄、成員結算、代墊還款（保留列順序 → sort_order）
//   - 不搬：Checklist、Checklist模板、財務預估
//   - 目標庫已經有任何財務資料就拒絕執行（避免重複搬）；整個過程一個交易，失敗就全部不寫
// 用法：DATABASE_URL=... node scripts/migrate-from-sheet.mts <xlsx>
import { readFileSync } from "node:fs";
import pg from "pg";
import { readLegacyWorkbook } from "../lib/finance/sheet.ts";

const file = process.argv[2];
const url = process.env.DATABASE_URL;
if (!file || !url) throw new Error("用法：DATABASE_URL=... node scripts/migrate-from-sheet.mts <xlsx>");
const d = readLegacyWorkbook(readFileSync(file));
const split = (s: string) => s.split(",").map((x) => x.trim()).filter(Boolean);
const showType = (name: string) => (name.includes("專場") ? "special" : "other");

const client = new pg.Client({ connectionString: url });
await client.connect();
try {
  await client.query("begin");
  await client.query("set local app.actor = 'migration'");
  const { rows: [existing] } = await client.query(
    "select (select count(*) from transactions) + (select count(*) from settlements) + (select count(*) from advance_repayments) as n",
  );
  if (Number(existing.n) > 0) throw new Error(`目標資料庫已經有 ${existing.n} 筆財務資料，拒絕重複搬家`);

  // 專案：同名已存在（例如在新平台先建好的月號）就沿用並補上 legacy_row
  const showIds = new Map<string, string>();
  const upsertShow = async (name: string, row: number | null) => {
    const { rows } = await client.query(
      `insert into shows (name, type, legacy_row) values ($1, $2, $3)
       on conflict (name) do update set legacy_row = coalesce(shows.legacy_row, excluded.legacy_row)
       returning id`,
      [name, showType(name), row],
    );
    showIds.set(name, rows[0].id);
  };
  for (const s of d.shows) await upsertShow(s.name, s.row);
  for (const t of d.transactions) if (!showIds.has(t.showName)) await upsertShow(t.showName, null); // 收支裡有、清單裡沒有的專案

  for (const t of d.transactions) {
    await client.query(
      `insert into transactions (id, show_id, category, notes, amount, advanced_by, excluded_members, date, recorded_by, paid_by_fund, auto_generated, sort_order)
       values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
      [t.id, showIds.get(t.showName), t.category, t.notes, t.amount, t.advancedBy || null, split(t.excludedMembers),
       t.date, t.recordedBy || null, t.paidByFund, t.autoGenerated, t.row],
    );
  }
  for (const [table, list] of [["settlements", d.settlements], ["advance_repayments", d.repayments]] as const) {
    for (const r of list) {
      await client.query(`insert into ${table} (member, amount, date, notes, sort_order) values ($1, $2, $3, $4, $5)`, [r.member, r.amount, r.date, r.notes, r.row]);
    }
  }
  // 之後新增的列要排在舊資料後面
  for (const table of ["transactions", "settlements", "advance_repayments"]) {
    await client.query(`select setval(pg_get_serial_sequence('${table}', 'sort_order'), greatest((select max(sort_order) from ${table}), 1))`);
  }
  await client.query("commit");
  console.log(`搬家完成：專案 ${showIds.size}（清單 ${d.shows.length}）、收支 ${d.transactions.length}、成員結算 ${d.settlements.length}、代墊還款 ${d.repayments.length}`);
} catch (err) {
  await client.query("rollback");
  console.error(`搬家失敗，已全部復原：${err instanceof Error ? err.message : err}`);
  process.exitCode = 1;
} finally {
  await client.end();
}
