// 對帳報告。用法：
//   node scripts/reconcile.mts sheet  <xlsx> <oracle.json>   用 Sheet 資料跑新程式（驗證計算規則本身）
//   node scripts/reconcile.mts db     <oracle.json>           用資料庫資料跑新程式（驗證搬家結果）；連線用 DATABASE_URL
// 任何一項不符就以非 0 結束，只印「不符的項目」與總結。
import { readFileSync } from "node:fs";
import pg from "pg";
import { readLegacyWorkbook } from "../lib/finance/sheet.ts";
import { reconcile, type Oracle } from "../lib/finance/reconcile.ts";
import type { Ledger, Tx } from "../lib/finance/calc.ts";

const [mode, a1, a2] = process.argv.slice(2);
let txs: Tx[]; let settlements: Ledger[]; let repayments: Ledger[]; let counts: Record<string, number>; let oracle: Oracle;

const split = (s: string) => s.split(",").map((x) => x.trim()).filter(Boolean);

if (mode === "sheet") {
  const d = readLegacyWorkbook(readFileSync(a1));
  oracle = JSON.parse(readFileSync(a2, "utf8"));
  txs = d.transactions.map((t) => ({
    id: t.id, showName: t.showName, category: t.category, notes: t.notes, amount: t.amount,
    advancedBy: t.advancedBy || null, excludedMembers: split(t.excludedMembers), date: t.date,
    recordedBy: t.recordedBy || null, paidByFund: t.paidByFund, autoGenerated: t.autoGenerated, sortOrder: t.row,
  }));
  settlements = d.settlements.map((r) => ({ id: String(r.row), member: r.member, amount: r.amount, date: r.date, notes: r.notes, sortOrder: r.row }));
  repayments = d.repayments.map((r) => ({ id: String(r.row), member: r.member, amount: r.amount, date: r.date, notes: r.notes, sortOrder: r.row }));
  counts = { shows: d.shows.length, transactions: txs.length, settlements: settlements.length, repayments: repayments.length };
} else if (mode === "db") {
  oracle = JSON.parse(readFileSync(a1, "utf8"));
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("請設定 DATABASE_URL");
  const client = new pg.Client({ connectionString: url });
  await client.connect();
  const q = async <T,>(sql: string) => (await client.query(sql)).rows as T[];
  txs = (await q<Record<string, unknown>>(`
    select t.id, s.name as show_name, t.category, t.notes, t.amount::float8 as amount, t.advanced_by, t.excluded_members,
           to_char(t.date, 'YYYY-MM-DD') as date, t.recorded_by, t.paid_by_fund, t.auto_generated, t.sort_order::float8 as sort_order
      from transactions t join shows s on s.id = t.show_id where t.deleted_at is null`)).map((r) => ({
    id: String(r.id), showName: String(r.show_name), category: String(r.category), notes: String(r.notes), amount: Number(r.amount),
    advancedBy: (r.advanced_by as string) || null, excludedMembers: (r.excluded_members as string[]) ?? [], date: String(r.date),
    recordedBy: (r.recorded_by as string) || null, paidByFund: Boolean(r.paid_by_fund), autoGenerated: Boolean(r.auto_generated), sortOrder: Number(r.sort_order),
  }));
  const ledger = async (table: string) => (await q<Record<string, unknown>>(
    `select id, member, amount::float8 as amount, to_char(date,'YYYY-MM-DD') as date, notes, sort_order::float8 as sort_order from ${table} where deleted_at is null`,
  )).map((r) => ({ id: String(r.id), member: String(r.member), amount: Number(r.amount), date: String(r.date), notes: String(r.notes), sortOrder: Number(r.sort_order) }));
  settlements = await ledger("settlements");
  repayments = await ledger("advance_repayments");
  const [{ n: showCount }] = await q<{ n: number }>("select count(*)::int as n from shows where legacy_row is not null");
  counts = { shows: showCount, transactions: txs.length, settlements: settlements.length, repayments: repayments.length };
  await client.end();
} else {
  throw new Error("用法：reconcile.mts sheet <xlsx> <oracle.json> | db <oracle.json>");
}

const checks = reconcile(oracle, txs, settlements, repayments, counts);
const failed = checks.filter((c) => !c.pass);
for (const c of failed) console.log(`❌ ${c.check}：舊 ${c.old} ／ 新 ${c.new}`);
console.log(`\n對帳結果：${checks.length - failed.length}/${checks.length} 項一致${failed.length ? `，${failed.length} 項不符` : "，全部一致 ✅"}`);
process.exit(failed.length ? 1 : 0);
